plugins {
    id 'java'
}

group = 'com.gamerlegend'
version = '1.0.0'
description = 'High Energy - Paper plugin'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

tasks.named('jar') {
    archiveBaseName = 'HighEnergy-Plugin'
    archiveVersion = ''
    archiveClassifier = ''
}
